#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp_dir="$(mktemp -d -t trans-release-tests.XXXXXX)"
trap 'rm -rf "$tmp_dir"' EXIT

fail() {
  echo "release script test failed: $1" >&2
  exit 1
}

assert_contains() {
  local output="$1"
  local expected="$2"
  [[ "$output" == *"$expected"* ]] || fail "expected output to contain: $expected"
}

assert_not_contains() {
  local output="$1"
  local unexpected="$2"
  [[ "$output" != *"$unexpected"* ]] || fail "expected output not to contain: $unexpected"
}

create_fixture() {
  local name="$1"
  local cargo_version="${2:-0.1.0}"
  local fixture="$tmp_dir/$name"
  local remote="$tmp_dir/$name.git"
  mkdir -p "$fixture/mock-bin"
  git init --quiet --bare "$remote"
  git init --quiet --initial-branch=main "$fixture"

  cp "$repo_root/release.sh" "$fixture/release.sh"
  chmod +x "$fixture/release.sh"

  cat >"$fixture/Cargo.toml" <<TOML
[package]
name = "release-fixture"
version = "$cargo_version"
edition = "2024"
TOML

  cat >"$fixture/Cargo.lock" <<LOCK
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "release-fixture"
version = "$cargo_version"
LOCK

  cat >"$fixture/mock-bin/gh" <<'MOCK_GH'
#!/usr/bin/env bash
set -euo pipefail

case "${1:-} ${2:-}" in
  "release create")
    echo "mock release command output" >&2
    echo "https://github.com/example/trans/releases/tag/${3}"
    ;;
  "release view")
    echo "https://github.com/example/trans/releases/tag/${3}"
    ;;
  "pr list")
    if [[ " $* " != *" --head update-trans-v0.1.1 "* ]]; then
      echo "Homebrew PR query used an unexpected head branch: $*" >&2
      exit 1
    fi
    printf '%s\n' "${MOCK_PR_URL:-}"
    ;;
  *)
    echo "unexpected gh invocation: $*" >&2
    exit 1
    ;;
esac
MOCK_GH

  cat >"$fixture/mock-bin/cargo" <<'MOCK_CARGO'
#!/usr/bin/env bash
echo "mock cargo command output" >&2
MOCK_CARGO

  cat >"$fixture/mock-bin/codex" <<'MOCK_CODEX'
#!/usr/bin/env bash
echo "mock codex command output" >&2
exit 1
MOCK_CODEX

  chmod +x "$fixture/mock-bin/gh" "$fixture/mock-bin/cargo" "$fixture/mock-bin/codex"

  git -C "$fixture" config user.email "release-tests@example.com"
  git -C "$fixture" config user.name "Release Tests"
  git -C "$fixture" add .
  git -C "$fixture" commit --quiet -m "feat: initial fixture"
  git -C "$fixture" remote add origin "$remote"

  printf '%s\n' "$fixture"
}

test_dry_run_progress() {
  local fixture
  fixture="$(create_fixture dry-run)"
  local output
  output="$(
    cd "$fixture"
    printf '\n\n' | PATH="$fixture/mock-bin:$PATH" ./release.sh patch --dry-run 2>&1
  )"

  assert_contains "$output" "ok  Check release tools"
  assert_contains "$output" "ok  Resolve release version"
  assert_contains "$output" "ok  Prepare changelog"
  assert_contains "$output" "ok  Complete dry run"
  assert_contains "$output" "Dry run complete. No version bump, tag, or release created."
  if git -C "$fixture" rev-parse --verify refs/tags/v0.1.1 >/dev/null 2>&1; then
    fail "dry run created a tag"
  fi
}

test_failure_shows_captured_output() {
  local fixture
  fixture="$(create_fixture failure)"
  printf '\n# dirty\n' >>"$fixture/Cargo.toml"

  local output
  if output="$(
    cd "$fixture"
    PATH="$fixture/mock-bin:$PATH" ./release.sh v0.1.1 --notes "Notes" 2>&1
  )"; then
    fail "dirty-tree release unexpectedly succeeded"
  fi

  assert_contains "$output" "failed  Validate release state"
  assert_contains "$output" "Working tree is dirty. Commit or stash changes first."
  assert_contains "$output" "Step output:"
}

test_failed_version_bump_stops_release() {
  local fixture
  fixture="$(create_fixture invalid-version 0.1.0-alpha)"

  local output
  if output="$(
    cd "$fixture"
    PATH="$fixture/mock-bin:$PATH" ./release.sh patch --dry-run 2>&1
  )"; then
    fail "unsupported Cargo version unexpectedly succeeded"
  fi

  assert_contains "$output" "failed  Resolve release version"
  assert_contains "$output" "unsupported Cargo.toml version '0.1.0-alpha', expected x.y.z"
  assert_not_contains "$output" "Version to release: v"
}

test_non_main_branch_is_rejected() {
  local fixture
  fixture="$(create_fixture feature-branch)"
  git -C "$fixture" switch --quiet -c feature/not-main

  local output
  if output="$(
    cd "$fixture"
    PATH="$fixture/mock-bin:$PATH" ./release.sh v0.1.1 --notes "Notes" 2>&1
  )"; then
    fail "release from a feature branch unexpectedly succeeded"
  fi

  assert_contains "$output" "failed  Validate release state"
  assert_contains "$output" "Releases must be created from the main branch (current: feature/not-main)."
  if git -C "$fixture" rev-parse --verify refs/tags/v0.1.1 >/dev/null 2>&1; then
    fail "feature-branch release created a tag"
  fi
}

test_remote_tag_is_rejected_before_main_push() {
  local fixture
  fixture="$(create_fixture remote-tag)"
  git -C "$fixture" tag v0.1.1
  git -C "$fixture" push --quiet origin refs/tags/v0.1.1
  git -C "$fixture" tag --delete v0.1.1 >/dev/null

  local output
  if output="$(
    cd "$fixture"
    PATH="$fixture/mock-bin:$PATH" ./release.sh v0.1.1 --notes "Notes" 2>&1
  )"; then
    fail "release with an existing remote tag unexpectedly succeeded"
  fi

  assert_contains "$output" "failed  Validate release state"
  assert_contains "$output" "Tag v0.1.1 already exists on origin."
  grep -q 'version = "0.1.0"' "$fixture/Cargo.toml" \
    || fail "remote-tag rejection changed the Cargo version"
  if git --git-dir="$tmp_dir/remote-tag.git" show-ref --verify refs/heads/main >/dev/null 2>&1; then
    fail "remote-tag rejection pushed the main branch"
  fi
}

test_atomic_push_rejection_keeps_remote_unchanged() {
  local fixture
  fixture="$(create_fixture atomic-rejection)"
  cat >"$tmp_dir/atomic-rejection.git/hooks/update" <<'HOOK'
#!/usr/bin/env bash
if [[ "$1" == refs/tags/* ]]; then
  echo "tag updates are rejected for this test" >&2
  exit 1
fi
HOOK
  chmod +x "$tmp_dir/atomic-rejection.git/hooks/update"

  local output
  if output="$(
    cd "$fixture"
    PATH="$fixture/mock-bin:$PATH" ./release.sh v0.1.1 --notes "Notes" 2>&1
  )"; then
    fail "release with a rejected tag push unexpectedly succeeded"
  fi

  assert_contains "$output" "failed  Push release commit and tag"
  assert_contains "$output" "tag updates are rejected for this test"
  assert_not_contains "$output" "ok  Create GitHub release"
  if git --git-dir="$tmp_dir/atomic-rejection.git" show-ref --verify refs/heads/main >/dev/null 2>&1; then
    fail "atomic push rejection updated the remote main branch"
  fi
  if git --git-dir="$tmp_dir/atomic-rejection.git" show-ref --verify refs/tags/v0.1.1 >/dev/null 2>&1; then
    fail "atomic push rejection created the remote tag"
  fi
}

test_release_hides_noise_and_prints_pr() {
  local fixture
  fixture="$(create_fixture success)"
  local pr_url="https://github.com/mbuvarp/homebrew-trans/pull/123"
  local output
  output="$(
    cd "$fixture"
    MOCK_PR_URL="$pr_url" PATH="$fixture/mock-bin:$PATH" \
      ./release.sh v0.1.1 --notes "Notes" 2>&1
  )"

  assert_contains "$output" "ok  Check updated Cargo package"
  assert_contains "$output" "ok  Push release commit and tag"
  assert_contains "$output" "ok  Create GitHub release"
  assert_contains "$output" "ok  Find Homebrew update PR"
  assert_contains "$output" "Release: https://github.com/example/trans/releases/tag/v0.1.1"
  assert_contains "$output" "Homebrew PR: $pr_url"
  assert_contains "$output" "Do not merge the Homebrew PR directly."
  assert_contains "$output" "After all bottle checks pass, run the brew pr-pull workflow:"
  assert_contains "$output" "https://github.com/mbuvarp/homebrew-trans/actions/workflows/publish.yml"
  assert_contains "$output" "Enter the Homebrew PR number and its reviewed head SHA."
  assert_not_contains "$output" "mock cargo command output"
  assert_not_contains "$output" "mock release command output"
  grep -q 'version = "0.1.1"' "$fixture/Cargo.toml" || fail "Cargo version was not updated"
  git --git-dir="$tmp_dir/success.git" show refs/heads/main:Cargo.toml \
    | grep -q 'version = "0.1.1"' \
    || fail "release commit was not pushed to the remote main branch"
  git --git-dir="$tmp_dir/success.git" rev-parse --verify refs/tags/v0.1.1 >/dev/null \
    || fail "release tag was not pushed to the remote"
  git -C "$fixture" rev-parse --verify refs/tags/v0.1.1 >/dev/null || fail "release tag was not created"
}

test_missing_pr_is_non_fatal() {
  local fixture
  fixture="$(create_fixture missing-pr)"
  local output
  output="$(
    cd "$fixture"
    HOMEBREW_PR_WAIT_SECONDS=0 PATH="$fixture/mock-bin:$PATH" \
      ./release.sh v0.1.1 --notes "Notes" 2>&1
  )"

  assert_contains "$output" "--  Homebrew PR is not available yet"
  assert_contains "$output" "Homebrew PR: not available yet"
  assert_contains "$output" "Release v0.1.1 created."
}

test_dry_run_progress
test_failure_shows_captured_output
test_failed_version_bump_stops_release
test_non_main_branch_is_rejected
test_remote_tag_is_rejected_before_main_push
test_atomic_push_rejection_keeps_remote_unchanged
test_release_hides_noise_and_prints_pr
test_missing_pr_is_non_fatal

echo "release script tests passed"
