#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp_dir="$(mktemp -d -t trans-release-tests.XXXXXX)"
trap 'rm -rf "$tmp_dir"' EXIT

fail() {
  echo "release script test failed: $1" >&2
  exit 1
}

assert_contains() {
  local output="$1"
  local expected="$2"
  [[ "$output" == *"$expected"* ]] || fail "expected output to contain: $expected"
}

assert_not_contains() {
  local output="$1"
  local unexpected="$2"
  [[ "$output" != *"$unexpected"* ]] || fail "expected output not to contain: $unexpected"
}

create_fixture() {
  local name="$1"
  local cargo_version="${2:-0.1.0}"
  local fixture="$tmp_dir/$name"
  local remote="$tmp_dir/$name.git"
  mkdir -p "$fixture/mock-bin"
  git init --quiet --bare "$remote"
  git init --quiet --initial-branch=main "$fixture"

  cp "$repo_root/release.sh" "$fixture/release.sh"
  chmod +x "$fixture/release.sh"

  cat >"$fixture/Cargo.toml" <<TOML
[package]
name = "release-fixture"
version = "$cargo_version"
edition = "2024"
TOML

  cat >"$fixture/Cargo.lock" <<LOCK
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "release-fixture"
version = "$cargo_version"
LOCK

  cat >"$fixture/mock-bin/gh" <<'MOCK_GH'
#!/usr/bin/env bash
set -euo pipefail

if [[ -n "${MOCK_GH_LOG:-}" ]]; then
  printf '%s\n' "$*" >>"$MOCK_GH_LOG"
fi

case "${1:-} ${2:-}" in
  "release create")
    echo "mock release command output" >&2
    echo "https://github.com/example/trans/releases/tag/${3}"
    ;;
  "release view")
    echo "https://github.com/example/trans/releases/tag/${3}"
    ;;
  "pr list")
    if [[ " $* " != *" --head update-trans-v0.1.1 "* ]]; then
      echo "Homebrew PR query used an unexpected head branch: $*" >&2
      exit 1
    fi
    if [[ -n "${MOCK_PR_URL:-}" ]]; then
      printf '%s\t%s\t%s\t%s\n' \
        "${MOCK_PR_NUMBER:-123}" \
        "$MOCK_PR_URL" \
        "${MOCK_PR_SHA:-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}" \
        "${MOCK_PR_BRANCH:-update-trans-v0.1.1}"
    fi
    ;;
  "pr checks")
    case "${MOCK_CHECKS_MODE:-pass}" in
      pass)
        printf '%s\n' '[{"name":"test-bot-macos (macos-15-intel)","bucket":"pass","state":"SUCCESS"},{"name":"test-bot-macos (macos-26)","bucket":"pass","state":"SUCCESS"},{"name":"test-bot-linux","bucket":"pass","state":"SUCCESS"}]'
        ;;
      fail)
        printf '%s\n' '[{"name":"test-bot-macos (macos-15-intel)","bucket":"pass","state":"SUCCESS"},{"name":"test-bot-macos (macos-26)","bucket":"fail","state":"FAILURE"},{"name":"test-bot-linux","bucket":"pass","state":"SUCCESS"}]'
        exit 1
        ;;
      pending-then-pass)
        state_file="${MOCK_GH_STATE_FILE:?MOCK_GH_STATE_FILE is required}"
        if [[ ! -f "$state_file" ]]; then
          : >"$state_file"
          printf '%s\n' '[{"name":"test-bot-macos (macos-15-intel)","bucket":"pass","state":"SUCCESS"},{"name":"test-bot-macos (macos-26)","bucket":"pending","state":"IN_PROGRESS"},{"name":"test-bot-linux","bucket":"pass","state":"SUCCESS"}]'
          exit 8
        fi
        printf '%s\n' '[{"name":"test-bot-macos (macos-15-intel)","bucket":"pass","state":"SUCCESS"},{"name":"test-bot-macos (macos-26)","bucket":"pass","state":"SUCCESS"},{"name":"test-bot-linux","bucket":"pass","state":"SUCCESS"}]'
        ;;
      *)
        echo "unexpected MOCK_CHECKS_MODE: $MOCK_CHECKS_MODE" >&2
        exit 1
        ;;
    esac
    ;;
  "pr view")
    printf '%s\t%s\t%s\t%s\n' \
      "${MOCK_PR_STATE:-OPEN}" \
      "${MOCK_CURRENT_PR_SHA:-${MOCK_PR_SHA:-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}}" \
      "${MOCK_PR_BRANCH:-update-trans-v0.1.1}" \
      "${MOCK_PR_REPOSITORY:-mbuvarp/homebrew-trans}"
    ;;
  "api user")
    echo "mbuvarp"
    ;;
  "run list")
    if [[ " $* " == *" --json databaseId "* ]]; then
      echo "111111111"
    else
      printf '%s\t%s\n' "111111111" "https://github.com/mbuvarp/homebrew-trans/actions/runs/111111111"
      if [[ -n "${MOCK_DISPATCH_MARKER:-}" \
        && -f "$MOCK_DISPATCH_MARKER" \
        && "${MOCK_RUN_LOOKUP_MODE:-found}" == "found" ]]; then
        printf '%s\t%s\n' "987654321" "https://github.com/mbuvarp/homebrew-trans/actions/runs/987654321"
      fi
    fi
    ;;
  "workflow run")
    if [[ -n "${MOCK_DISPATCH_MARKER:-}" ]]; then
      : >"$MOCK_DISPATCH_MARKER"
    fi
    if [[ "${MOCK_WORKFLOW_URL:-return}" == "return" ]]; then
      echo "https://github.com/mbuvarp/homebrew-trans/actions/runs/987654321"
    fi
    ;;
  "run watch")
    if [[ "${MOCK_PUBLISH_RESULT:-success}" == "failure" ]]; then
      echo "mock brew pr-pull failure" >&2
      exit 1
    fi
    echo "mock brew pr-pull success"
    ;;
  *)
    echo "unexpected gh invocation: $*" >&2
    exit 1
    ;;
esac
MOCK_GH

  cat >"$fixture/mock-bin/cargo" <<'MOCK_CARGO'
#!/usr/bin/env bash
echo "mock cargo command output" >&2
MOCK_CARGO

  cat >"$fixture/mock-bin/codex" <<'MOCK_CODEX'
#!/usr/bin/env bash
echo "mock codex command output" >&2
exit 1
MOCK_CODEX

  chmod +x "$fixture/mock-bin/gh" "$fixture/mock-bin/cargo" "$fixture/mock-bin/codex"

  git -C "$fixture" config user.email "release-tests@example.com"
  git -C "$fixture" config user.name "Release Tests"
  git -C "$fixture" add .
  git -C "$fixture" commit --quiet -m "feat: initial fixture"
  git -C "$fixture" remote add origin "$remote"

  printf '%s\n' "$fixture"
}

test_dry_run_progress() {
  local fixture
  fixture="$(create_fixture dry-run)"
  local output
  output="$(
    cd "$fixture"
    printf '\n\n' | PATH="$fixture/mock-bin:$PATH" ./release.sh patch --dry-run 2>&1
  )"

  assert_contains "$output" "ok  Check release tools"
  assert_contains "$output" "ok  Resolve release version"
  assert_contains "$output" "ok  Prepare changelog"
  assert_contains "$output" "ok  Complete dry run"
  assert_contains "$output" "Dry run complete. No version bump, tag, or release created."
  if git -C "$fixture" rev-parse --verify refs/tags/v0.1.1 >/dev/null 2>&1; then
    fail "dry run created a tag"
  fi
}

test_failure_shows_captured_output() {
  local fixture
  fixture="$(create_fixture failure)"
  printf '\n# dirty\n' >>"$fixture/Cargo.toml"

  local output
  if output="$(
    cd "$fixture"
    PATH="$fixture/mock-bin:$PATH" ./release.sh v0.1.1 --notes "Notes" 2>&1
  )"; then
    fail "dirty-tree release unexpectedly succeeded"
  fi

  assert_contains "$output" "failed  Validate release state"
  assert_contains "$output" "Working tree is dirty. Commit or stash changes first."
  assert_contains "$output" "Step output:"
}

test_failed_version_bump_stops_release() {
  local fixture
  fixture="$(create_fixture invalid-version 0.1.0-alpha)"

  local output
  if output="$(
    cd "$fixture"
    PATH="$fixture/mock-bin:$PATH" ./release.sh patch --dry-run 2>&1
  )"; then
    fail "unsupported Cargo version unexpectedly succeeded"
  fi

  assert_contains "$output" "failed  Resolve release version"
  assert_contains "$output" "unsupported Cargo.toml version '0.1.0-alpha', expected x.y.z"
  assert_not_contains "$output" "Version to release: v"
}

test_non_main_branch_is_rejected() {
  local fixture
  fixture="$(create_fixture feature-branch)"
  git -C "$fixture" switch --quiet -c feature/not-main

  local output
  if output="$(
    cd "$fixture"
    PATH="$fixture/mock-bin:$PATH" ./release.sh v0.1.1 --notes "Notes" 2>&1
  )"; then
    fail "release from a feature branch unexpectedly succeeded"
  fi

  assert_contains "$output" "failed  Validate release state"
  assert_contains "$output" "Releases must be created from the main branch (current: feature/not-main)."
  if git -C "$fixture" rev-parse --verify refs/tags/v0.1.1 >/dev/null 2>&1; then
    fail "feature-branch release created a tag"
  fi
}

test_remote_tag_is_rejected_before_main_push() {
  local fixture
  fixture="$(create_fixture remote-tag)"
  git -C "$fixture" tag v0.1.1
  git -C "$fixture" push --quiet origin refs/tags/v0.1.1
  git -C "$fixture" tag --delete v0.1.1 >/dev/null

  local output
  if output="$(
    cd "$fixture"
    PATH="$fixture/mock-bin:$PATH" ./release.sh v0.1.1 --notes "Notes" 2>&1
  )"; then
    fail "release with an existing remote tag unexpectedly succeeded"
  fi

  assert_contains "$output" "failed  Validate release state"
  assert_contains "$output" "Tag v0.1.1 already exists on origin."
  grep -q 'version = "0.1.0"' "$fixture/Cargo.toml" \
    || fail "remote-tag rejection changed the Cargo version"
  if git --git-dir="$tmp_dir/remote-tag.git" show-ref --verify refs/heads/main >/dev/null 2>&1; then
    fail "remote-tag rejection pushed the main branch"
  fi
}

test_atomic_push_rejection_keeps_remote_unchanged() {
  local fixture
  fixture="$(create_fixture atomic-rejection)"
  cat >"$tmp_dir/atomic-rejection.git/hooks/update" <<'HOOK'
#!/usr/bin/env bash
if [[ "$1" == refs/tags/* ]]; then
  echo "tag updates are rejected for this test" >&2
  exit 1
fi
HOOK
  chmod +x "$tmp_dir/atomic-rejection.git/hooks/update"

  local output
  if output="$(
    cd "$fixture"
    PATH="$fixture/mock-bin:$PATH" ./release.sh v0.1.1 --notes "Notes" 2>&1
  )"; then
    fail "release with a rejected tag push unexpectedly succeeded"
  fi

  assert_contains "$output" "failed  Push release commit and tag"
  assert_contains "$output" "tag updates are rejected for this test"
  assert_not_contains "$output" "ok  Create GitHub release"
  if git --git-dir="$tmp_dir/atomic-rejection.git" show-ref --verify refs/heads/main >/dev/null 2>&1; then
    fail "atomic push rejection updated the remote main branch"
  fi
  if git --git-dir="$tmp_dir/atomic-rejection.git" show-ref --verify refs/tags/v0.1.1 >/dev/null 2>&1; then
    fail "atomic push rejection created the remote tag"
  fi
}

test_release_hides_noise_and_prints_pr() {
  local fixture
  fixture="$(create_fixture success)"
  local pr_url="https://github.com/mbuvarp/homebrew-trans/pull/123"
  local output
  output="$(
    cd "$fixture"
    MOCK_PR_URL="$pr_url" PATH="$fixture/mock-bin:$PATH" \
      ./release.sh v0.1.1 --notes "Notes" 2>&1
  )"

  assert_contains "$output" "ok  Check updated Cargo package"
  assert_contains "$output" "ok  Push release commit and tag"
  assert_contains "$output" "ok  Create GitHub release"
  assert_contains "$output" "ok  Find Homebrew update PR"
  assert_contains "$output" "Release: https://github.com/example/trans/releases/tag/v0.1.1"
  assert_contains "$output" "Homebrew PR: $pr_url"
  assert_contains "$output" "Wait for bottle checks and publish with brew pr-pull? [y/N]"
  assert_contains "$output" "--  Leave Homebrew bottle publishing for manual completion"
  assert_contains "$output" "Do not merge the Homebrew PR directly."
  assert_contains "$output" "After all bottle checks pass, run the brew pr-pull workflow:"
  assert_contains "$output" "https://github.com/mbuvarp/homebrew-trans/actions/workflows/publish.yml"
  assert_contains "$output" "Enter the Homebrew PR number and its reviewed head SHA."
  assert_not_contains "$output" "mock cargo command output"
  assert_not_contains "$output" "mock release command output"
  grep -q 'version = "0.1.1"' "$fixture/Cargo.toml" || fail "Cargo version was not updated"
  git --git-dir="$tmp_dir/success.git" show refs/heads/main:Cargo.toml \
    | grep -q 'version = "0.1.1"' \
    || fail "release commit was not pushed to the remote main branch"
  git --git-dir="$tmp_dir/success.git" rev-parse --verify refs/tags/v0.1.1 >/dev/null \
    || fail "release tag was not pushed to the remote"
  git -C "$fixture" rev-parse --verify refs/tags/v0.1.1 >/dev/null || fail "release tag was not created"
}

test_automated_homebrew_publish_waits_and_dispatches() {
  local fixture
  fixture="$(create_fixture automated-publish)"
  local pr_url="https://github.com/mbuvarp/homebrew-trans/pull/123"
  local gh_log="$fixture/gh.log"
  local gh_state="$fixture/gh-state"
  local output
  output="$(
    cd "$fixture"
    printf 'y\n' | env \
      MOCK_PR_URL="$pr_url" \
      MOCK_CHECKS_MODE=pending-then-pass \
      MOCK_GH_STATE_FILE="$gh_state" \
      MOCK_GH_LOG="$gh_log" \
      HOMEBREW_CHECK_POLL_SECONDS=1 \
      PATH="$fixture/mock-bin:$PATH" \
      ./release.sh v0.1.1 --notes "Notes" 2>&1
  )"

  assert_contains "$output" "ok  Wait for Homebrew bottle checks"
  assert_contains "$output" "ok  Verify reviewed Homebrew PR head"
  assert_contains "$output" "ok  Start brew pr-pull workflow"
  assert_contains "$output" "ok  Wait for brew pr-pull workflow"
  assert_contains "$output" "Published with brew pr-pull: https://github.com/mbuvarp/homebrew-trans/actions/runs/987654321"
  grep -q "workflow run publish.yml --repo mbuvarp/homebrew-trans --ref main --raw-field pull_request=123 --raw-field head_sha=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" "$gh_log" \
    || fail "brew pr-pull workflow was not dispatched with the reviewed PR head"
  grep -q "run watch 987654321 --repo mbuvarp/homebrew-trans --exit-status --compact --interval 1" "$gh_log" \
    || fail "brew pr-pull workflow was not watched"
}

test_missing_dispatch_url_finds_and_watches_new_run() {
  local fixture
  fixture="$(create_fixture dispatch-url-fallback)"
  local gh_log="$fixture/gh.log"
  local dispatch_marker="$fixture/dispatched"
  local output
  output="$(
    cd "$fixture"
    printf 'y\n' | env \
      MOCK_PR_URL="https://github.com/mbuvarp/homebrew-trans/pull/123" \
      MOCK_WORKFLOW_URL=omit \
      MOCK_DISPATCH_MARKER="$dispatch_marker" \
      MOCK_GH_LOG="$gh_log" \
      PATH="$fixture/mock-bin:$PATH" \
      ./release.sh v0.1.1 --notes "Notes" 2>&1
  )"

  assert_contains "$output" "ok  Start brew pr-pull workflow"
  assert_contains "$output" "ok  Wait for brew pr-pull workflow"
  assert_contains "$output" "Published with brew pr-pull: https://github.com/mbuvarp/homebrew-trans/actions/runs/987654321"
  grep -q "run watch 987654321" "$gh_log" \
    || fail "fallback publish run was not watched"
  if [[ "$(grep -c '^workflow run ' "$gh_log")" -ne 1 ]]; then
    fail "fallback dispatched the brew pr-pull workflow more than once"
  fi
}

test_unresolved_dispatch_url_reports_started_workflow() {
  local fixture
  fixture="$(create_fixture dispatch-url-unresolved)"
  local gh_log="$fixture/gh.log"
  local dispatch_marker="$fixture/dispatched"
  local output
  output="$(
    cd "$fixture"
    printf 'y\n' | env \
      MOCK_PR_URL="https://github.com/mbuvarp/homebrew-trans/pull/123" \
      MOCK_WORKFLOW_URL=omit \
      MOCK_DISPATCH_MARKER="$dispatch_marker" \
      MOCK_RUN_LOOKUP_MODE=missing \
      MOCK_GH_LOG="$gh_log" \
      HOMEBREW_RUN_LOOKUP_WAIT_SECONDS=0 \
      PATH="$fixture/mock-bin:$PATH" \
      ./release.sh v0.1.1 --notes "Notes" 2>&1
  )"

  assert_contains "$output" "ok  Start brew pr-pull workflow"
  assert_contains "$output" "--  brew pr-pull started; run URL is not available"
  assert_contains "$output" "The brew pr-pull workflow was dispatched, but its run URL is unavailable."
  assert_contains "$output" "Check its status at https://github.com/mbuvarp/homebrew-trans/actions/workflows/publish.yml"
  assert_not_contains "$output" "After all bottle checks pass, run the brew pr-pull workflow:"
  if grep -q "run watch" "$gh_log"; then
    fail "release attempted to watch an unidentified workflow run"
  fi
  if [[ "$(grep -c '^workflow run ' "$gh_log")" -ne 1 ]]; then
    fail "missing run URL caused a duplicate brew pr-pull dispatch"
  fi
}

test_failed_homebrew_check_prevents_publish() {
  local fixture
  fixture="$(create_fixture failed-check)"
  local gh_log="$fixture/gh.log"
  local output
  if output="$(
    cd "$fixture"
    printf 'y\n' | env \
      MOCK_PR_URL="https://github.com/mbuvarp/homebrew-trans/pull/123" \
      MOCK_CHECKS_MODE=fail \
      MOCK_GH_LOG="$gh_log" \
      PATH="$fixture/mock-bin:$PATH" \
      ./release.sh v0.1.1 --notes "Notes" 2>&1
  )"; then
    fail "release published Homebrew bottles after a failed check"
  fi

  assert_contains "$output" "failed  Wait for Homebrew bottle checks"
  assert_contains "$output" "Homebrew checks did not succeed: test-bot-macos (macos-26)"
  if grep -q "workflow run" "$gh_log"; then
    fail "brew pr-pull workflow was dispatched after a failed check"
  fi
}

test_changed_homebrew_head_prevents_publish() {
  local fixture
  fixture="$(create_fixture changed-head)"
  local gh_log="$fixture/gh.log"
  local output
  if output="$(
    cd "$fixture"
    printf 'y\n' | env \
      MOCK_PR_URL="https://github.com/mbuvarp/homebrew-trans/pull/123" \
      MOCK_CURRENT_PR_SHA="bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb" \
      MOCK_GH_LOG="$gh_log" \
      PATH="$fixture/mock-bin:$PATH" \
      ./release.sh v0.1.1 --notes "Notes" 2>&1
  )"; then
    fail "release published Homebrew bottles after the PR head changed"
  fi

  assert_contains "$output" "failed  Verify reviewed Homebrew PR head"
  assert_contains "$output" "changed head SHA while checks were running"
  if grep -q "workflow run" "$gh_log"; then
    fail "brew pr-pull workflow was dispatched after the PR head changed"
  fi
}

test_missing_pr_is_non_fatal() {
  local fixture
  fixture="$(create_fixture missing-pr)"
  local output
  output="$(
    cd "$fixture"
    HOMEBREW_PR_WAIT_SECONDS=0 PATH="$fixture/mock-bin:$PATH" \
      ./release.sh v0.1.1 --notes "Notes" 2>&1
  )"

  assert_contains "$output" "--  Homebrew PR is not available yet"
  assert_contains "$output" "Homebrew PR: not available yet"
  assert_contains "$output" "Release v0.1.1 created."
  assert_not_contains "$output" "Wait for bottle checks and publish with brew pr-pull?"
}

test_dry_run_progress
test_failure_shows_captured_output
test_failed_version_bump_stops_release
test_non_main_branch_is_rejected
test_remote_tag_is_rejected_before_main_push
test_atomic_push_rejection_keeps_remote_unchanged
test_release_hides_noise_and_prints_pr
test_automated_homebrew_publish_waits_and_dispatches
test_missing_dispatch_url_finds_and_watches_new_run
test_unresolved_dispatch_url_reports_started_workflow
test_failed_homebrew_check_prevents_publish
test_changed_homebrew_head_prevents_publish
test_missing_pr_is_non_fatal

echo "release script tests passed"
