#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp_dir="$(mktemp -d -t trans-release-tests.XXXXXX)"
trap 'rm -rf "$tmp_dir"' EXIT

fail() {
  echo "release script test failed: $1" >&2
  exit 1
}

assert_contains() {
  local output="$1"
  local expected="$2"
  [[ "$output" == *"$expected"* ]] || fail "expected output to contain: $expected"
}

assert_not_contains() {
  local output="$1"
  local unexpected="$2"
  [[ "$output" != *"$unexpected"* ]] || fail "expected output not to contain: $unexpected"
}

create_fixture() {
  local name="$1"
  local fixture="$tmp_dir/$name"
  local remote="$tmp_dir/$name.git"
  mkdir -p "$fixture/mock-bin"
  git init --quiet --bare "$remote"
  git init --quiet --initial-branch=main "$fixture"

  cp "$repo_root/release.sh" "$fixture/release.sh"
  chmod +x "$fixture/release.sh"

  cat >"$fixture/Cargo.toml" <<'TOML'
[package]
name = "release-fixture"
version = "0.1.0"
edition = "2024"
TOML

  cat >"$fixture/Cargo.lock" <<'LOCK'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "release-fixture"
version = "0.1.0"
LOCK

  cat >"$fixture/mock-bin/gh" <<'MOCK_GH'
#!/usr/bin/env bash
set -euo pipefail

case "${1:-} ${2:-}" in
  "release create")
    echo "mock release command output" >&2
    echo "https://github.com/example/trans/releases/tag/${3}"
    ;;
  "release view")
    echo "https://github.com/example/trans/releases/tag/${3}"
    ;;
  "pr list")
    if [[ " $* " != *" --head update-trans-v0.1.1 "* ]]; then
      echo "Homebrew PR query used an unexpected head branch: $*" >&2
      exit 1
    fi
    printf '%s\n' "${MOCK_PR_URL:-}"
    ;;
  *)
    echo "unexpected gh invocation: $*" >&2
    exit 1
    ;;
esac
MOCK_GH

  cat >"$fixture/mock-bin/cargo" <<'MOCK_CARGO'
#!/usr/bin/env bash
echo "mock cargo command output" >&2
MOCK_CARGO

  cat >"$fixture/mock-bin/codex" <<'MOCK_CODEX'
#!/usr/bin/env bash
echo "mock codex command output" >&2
exit 1
MOCK_CODEX

  chmod +x "$fixture/mock-bin/gh" "$fixture/mock-bin/cargo" "$fixture/mock-bin/codex"

  git -C "$fixture" config user.email "release-tests@example.com"
  git -C "$fixture" config user.name "Release Tests"
  git -C "$fixture" add .
  git -C "$fixture" commit --quiet -m "feat: initial fixture"
  git -C "$fixture" remote add origin "$remote"

  printf '%s\n' "$fixture"
}

test_dry_run_progress() {
  local fixture
  fixture="$(create_fixture dry-run)"
  local output
  output="$(
    cd "$fixture"
    printf '\n\n' | PATH="$fixture/mock-bin:$PATH" ./release.sh patch --dry-run 2>&1
  )"

  assert_contains "$output" "ok  Check release tools"
  assert_contains "$output" "ok  Resolve release version"
  assert_contains "$output" "ok  Prepare changelog"
  assert_contains "$output" "ok  Complete dry run"
  assert_contains "$output" "Dry run complete. No version bump, tag, or release created."
  if git -C "$fixture" rev-parse --verify refs/tags/v0.1.1 >/dev/null 2>&1; then
    fail "dry run created a tag"
  fi
}

test_failure_shows_captured_output() {
  local fixture
  fixture="$(create_fixture failure)"
  printf '\n# dirty\n' >>"$fixture/Cargo.toml"

  local output
  if output="$(
    cd "$fixture"
    PATH="$fixture/mock-bin:$PATH" ./release.sh v0.1.1 --notes "Notes" 2>&1
  )"; then
    fail "dirty-tree release unexpectedly succeeded"
  fi

  assert_contains "$output" "failed  Validate release state"
  assert_contains "$output" "Working tree is dirty. Commit or stash changes first."
  assert_contains "$output" "Step output:"
}

test_release_hides_noise_and_prints_pr() {
  local fixture
  fixture="$(create_fixture success)"
  local pr_url="https://github.com/mbuvarp/homebrew-trans/pull/123"
  local output
  output="$(
    cd "$fixture"
    MOCK_PR_URL="$pr_url" PATH="$fixture/mock-bin:$PATH" \
      ./release.sh v0.1.1 --notes "Notes" 2>&1
  )"

  assert_contains "$output" "ok  Check updated Cargo package"
  assert_contains "$output" "ok  Create GitHub release"
  assert_contains "$output" "ok  Find Homebrew update PR"
  assert_contains "$output" "Release: https://github.com/example/trans/releases/tag/v0.1.1"
  assert_contains "$output" "Homebrew PR: $pr_url"
  assert_not_contains "$output" "mock cargo command output"
  assert_not_contains "$output" "mock release command output"
  grep -q 'version = "0.1.1"' "$fixture/Cargo.toml" || fail "Cargo version was not updated"
  git -C "$fixture" rev-parse --verify refs/tags/v0.1.1 >/dev/null || fail "release tag was not created"
}

test_missing_pr_is_non_fatal() {
  local fixture
  fixture="$(create_fixture missing-pr)"
  local output
  output="$(
    cd "$fixture"
    HOMEBREW_PR_WAIT_SECONDS=0 PATH="$fixture/mock-bin:$PATH" \
      ./release.sh v0.1.1 --notes "Notes" 2>&1
  )"

  assert_contains "$output" "--  Homebrew PR is not available yet"
  assert_contains "$output" "Homebrew PR: not available yet"
  assert_contains "$output" "Release v0.1.1 created."
}

test_dry_run_progress
test_failure_shows_captured_output
test_release_hides_noise_and_prints_pr
test_missing_pr_is_non_fatal

echo "release script tests passed"
